// src/data/countryOptions.ts
export const countryOptions = [
    { 
      id: 'us', 
      countryCode: 'us', 
      countryName: 'United States', 
      currency: 'USD', 
    },
    { 
      id: 'eu', 
      countryCode: 'eu', 
      countryName: 'Eurozone', 
      currency: 'EUR', 
    },
    { 
      id: 'gb', 
      countryCode: 'gb', 
      countryName: 'United Kingdom', 
      currency: 'GBP', 
    },
    { 
      id: 'in', 
      countryCode: 'in', 
      countryName: 'India', 
      currency: 'INR', 
    },
    { 
      id: 'au', 
      countryCode: 'au', 
      countryName: 'Australia', 
      currency: 'AUD', 
    },
    { 
      id: 'jp', 
      countryCode: 'jp', 
      countryName: 'Japan', 
      currency: 'JPY', 
    },
    { 
      id: 'ca', 
      countryCode: 'ca', 
      countryName: 'Canada', 
      currency: 'CAD', 
    },
    { 
      id: 'ch', 
      countryCode: 'ch', 
      countryName: 'Switzerland', 
      currency: 'CHF', 
    },
    { 
      id: 'cn', 
      countryCode: 'cn', 
      countryName: 'China', 
      currency: 'CNY', 
    },
    { 
      id: 'mx', 
      countryCode: 'mx', 
      countryName: 'Mexico', 
      currency: 'MXN', 
    },
    { 
      id: 'br', 
      countryCode: 'br', 
      countryName: 'Brazil', 
      currency: 'BRL', 
    },
    { 
      id: 'za', 
      countryCode: 'za', 
      countryName: 'South Africa', 
      currency: 'ZAR', 
    },
    { 
      id: 'ru', 
      countryCode: 'ru', 
      countryName: 'Russia', 
      currency: 'RUB', 
    },
    { 
      id: 'sg', 
      countryCode: 'sg', 
      countryName: 'Singapore', 
      currency: 'SGD', 
    },
    { 
      id: 'se', 
      countryCode: 'se', 
      countryName: 'Sweden', 
      currency: 'SEK', 
    },
    { 
      id: 'no', 
      countryCode: 'no', 
      countryName: 'Norway', 
      currency: 'NOK', 
    },
    { 
      id: 'dk', 
      countryCode: 'dk', 
      countryName: 'Denmark', 
      currency: 'DKK', 
    },
    { 
      id: 'kr', 
      countryCode: 'kr', 
      countryName: 'South Korea', 
      currency: 'KRW', 
    },
    { 
      id: 'tw', 
      countryCode: 'tw', 
      countryName: 'Taiwan', 
      currency: 'TWD', 
    },
    { 
      id: 'th', 
      countryCode: 'th', 
      countryName: 'Thailand', 
      currency: 'THB', 
    },
    { 
      id: 'hk', 
      countryCode: 'hk', 
      countryName: 'Hong Kong', 
      currency: 'HKD', 
    },
    { 
      id: 'nz', 
      countryCode: 'nz', 
      countryName: 'New Zealand', 
      currency: 'NZD', 
    },
    { 
      id: 'pl', 
      countryCode: 'pl', 
      countryName: 'Poland', 
      currency: 'PLN', 
    },
    { 
      id: 'tr', 
      countryCode: 'tr', 
      countryName: 'Turkey', 
      currency: 'TRY', 
    },
    { 
      id: 'id', 
      countryCode: 'id', 
      countryName: 'Indonesia', 
      currency: 'IDR', 
    },
    { 
      id: 'sa', 
      countryCode: 'sa', 
      countryName: 'Saudi Arabia', 
      currency: 'SAR', 
    },
    { 
      id: 'my', 
      countryCode: 'my', 
      countryName: 'Malaysia', 
      currency: 'MYR', 
    },
    { 
      id: 'ph', 
      countryCode: 'ph', 
      countryName: 'Philippines', 
      currency: 'PHP', 
    },
    { 
      id: 'ae', 
      countryCode: 'ae', 
      countryName: 'United Arab Emirates', 
      currency: 'AED', 
    },
    { 
      id: 'eg', 
      countryCode: 'eg', 
      countryName: 'Egypt', 
      currency: 'EGP', 
    },
    { 
      id: 'co', 
      countryCode: 'co', 
      countryName: 'Colombia', 
      currency: 'COP', 
    },
    { 
      id: 'vn', 
      countryCode: 'vn', 
      countryName: 'Vietnam', 
      currency: 'VND', 
    },
    { 
      id: 'cl', 
      countryCode: 'cl', 
      countryName: 'Chile', 
      currency: 'CLP', 
    },
    { 
      id: 'pk', 
      countryCode: 'pk', 
      countryName: 'Pakistan', 
      currency: 'PKR', 
    },
    { 
      id: 'hu', 
      countryCode: 'hu', 
      countryName: 'Hungary', 
      currency: 'HUF', 
    },
    { 
      id: 'cz', 
      countryCode: 'cz', 
      countryName: 'Czech Republic', 
      currency: 'CZK', 
    },
    { 
      id: 'kw', 
      countryCode: 'kw', 
      countryName: 'Kuwait', 
      currency: 'KWD', 
    },
    { 
      id: 'qa', 
      countryCode: 'qa', 
      countryName: 'Qatar', 
      currency: 'QAR', 
    },
    { 
      id: 'om', 
      countryCode: 'om', 
      countryName: 'Oman', 
      currency: 'OMR', 
    },
    { 
      id: 'bh', 
      countryCode: 'bh', 
      countryName: 'Bahrain', 
      currency: 'BHD', 
    },
    { 
      id: 'jo', 
      countryCode: 'jo', 
      countryName: 'Jordan', 
      currency: 'JOD', 
    },
    { 
      id: 'ye', 
      countryCode: 'ye', 
      countryName: 'Yemen', 
      currency: 'YEN', 
    },
    { 
      id: 'ke', 
      countryCode: 'ke', 
      countryName: 'Kenya', 
      currency: 'KES', 
    },
    { 
      id: 'ug', 
      countryCode: 'ug', 
      countryName: 'Uganda', 
      currency: 'UGX', 
    },
    { 
      id: 'tz', 
      countryCode: 'tz', 
      countryName: 'Tanzania', 
      currency: 'TZS', 
    },
    { 
      id: 'rw', 
      countryCode: 'rw', 
      countryName: 'Rwanda', 
      currency: 'RWF', 
    },
    { 
      id: 'bb', 
      countryCode: 'bb', 
      countryName: 'Barbados', 
      currency: 'BBD', 
    },
    { 
      id: 'lr', 
      countryCode: 'lr', 
      countryName: 'Liberia', 
      currency: 'LRD', 
    },
    { 
      id: 'lk', 
      countryCode: 'lk', 
      countryName: 'Sri Lanka', 
      currency: 'LKR', 
    },
    { 
      id: 'mu', 
      countryCode: 'mu', 
      countryName: 'Mauritius', 
      currency: 'MUR', 
    },
    { 
      id: 'ma', 
      countryCode: 'ma', 
      countryName: 'Morocco', 
      currency: 'MAD', 
    },
    { 
      id: 'tn', 
      countryCode: 'tn', 
      countryName: 'Tunisia', 
      currency: 'TND', 
    },
    { 
      id: 'bg', 
      countryCode: 'bg', 
      countryName: 'Bulgaria', 
      currency: 'BGN', 
    },
    { 
      id: 'mk', 
      countryCode: 'mk', 
      countryName: 'North Macedonia', 
      currency: 'MKD', 
    },
    { 
      id: 'md', 
      countryCode: 'md', 
      countryName: 'Moldova', 
      currency: 'MDL', 
    },
    { 
      id: 'hn', 
      countryCode: 'hn', 
      countryName: 'Honduras', 
      currency: 'HNL', 
    },
    { 
      id: 'do', 
      countryCode: 'do', 
      countryName: 'Dominican Republic', 
      currency: 'DOP', 
    },
  ];
  